--liquibase formatted sql

--changeset carlosray:1
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 select count(1) from information_schema.tables where table_schema = 'public' and table_name = 'account';
create table account
(
    id          bigint generated by default as identity
        constraint pk_category
            primary key,
    name        varchar(255) not null,
    config      jsonb        not null,
    group_id    bigint       not null,
    created     timestamp    default now(),
    created_by  varchar(255) default CURRENT_USER,
    modified    timestamp    default now(),
    modified_by varchar(255) default CURRENT_USER
);
--rollback drop table account