version: '2'

services:

  postgres-common-cluster:
    container_name: postgres-common-cluster
    image: postgres
    volumes:
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=fa_auth,fa_user,fa_group,fa_category,fa_account
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: unless-stopped
    ports: [ "5432:5432" ]

