db:
  host: localhost
  port: 5432
  name: fa_user
  username: fa_user
  password: ""

pwd:
  encoder:
    strength: 10

token:
  internal-key: "default"

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters

spring:
  r2dbc:
    properties:
      ssl: false
      sslMode: disable
  kafka:
    server: localhost:9092