db:
  host: localhost
  port: 5432
  name: fa_group
  username: fa_group
  password: ""

token:
  internal-key: "default"

client:
  balance-service:
    uri: http://localhost:8008
  user-service:
    uri: http://localhost:8006

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
    space.ipvz.fa: DEBUG

spring:
  r2dbc:
    properties:
      ssl: false
      sslMode: disable
  kafka:
    server: localhost:9092