spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods: "*"
            maxAge: 3600
client:
  user-service:
    uri: http://localhost:8006
  auth-service:
    uri: http://localhost:8002
  operation-service:
    uri: http://localhost:8005
  group-service:
    uri: http://localhost:8004
  account-service:
    uri: http://localhost:8007
  category-service:
    uri: http://localhost:8003
