spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods: "*"
            maxAge: 3600
client:
  user-service:
    uri: http://localhost:8787
  auth-service:
    uri: http://localhost:8008

