spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      routes:
        #auth
        - id: auth_login
          uri: ${client.auth-service.uri}
          predicates:
            - Path=/api/auth/login
            - Method=POST
          filters:
            - SetPath=/auth/login

        - id: auth_refresh
          uri: ${client.auth-service.uri}
          predicates:
            - Path=/api/auth/refresh
            - Method=PUT
          filters:
            - SetPath=/auth/refresh

        #users
        - id: user_register
          uri: ${client.user-service.uri}
          predicates:
            - Path=/api/auth/register
            - Method=POST
          filters:
            - SetPath=/users

        - id: user_get_all
          uri: ${client.user-service.uri}
          predicates:
            - Path=/api/users
            - Method=GET
          filters:
            - StripPrefix=1
            - Auth

        #operations
        - id: operation_create
          uri: ${client.operation-service.uri}
          predicates:
            - Path=/api/operations
            - Method=POST
          filters:
            - SetPath=/operations
            - Auth

        - id: operation_get
          uri: ${client.operation-service.uri}
          predicates:
            - Path=/api/operations/group/**
            - Method=GET
          filters:
            - StripPrefix=1
            - Auth

        #group
        - id: groups_get
          uri: ${client.group-service.uri}
          predicates:
            - Path=/api/groups/**
            - Method=GET
          filters:
            - StripPrefix=1
            - Auth

        - id: groups_create
          uri: ${client.group-service.uri}
          predicates:
            - Path=/api/groups
            - Method=POST
          filters:
            - StripPrefix=1
            - Auth

        - id: groups_update
          uri: ${client.group-service.uri}
          predicates:
            - Path=/api/groups
            - Method=PUT
          filters:
            - StripPrefix=1
            - Auth

        - id: groups_delete
          uri: ${client.group-service.uri}
          predicates:
            - Path=/api/groups/**
            - Method=DELETE
          filters:
            - StripPrefix=1
            - Auth

        #account
        - id: account_get_all
          uri: ${client.account-service.uri}
          predicates:
            - Path=/api/accounts/group/**
            - Method=GET
          filters:
            - StripPrefix=1
            - Auth

        #category
        - id: category_get
          uri: ${client.category-service.uri}
          predicates:
            - Path=/api/categories/group/**
            - Method=GET
          filters:
            - StripPrefix=1
            - Auth

        - id: category_create
          uri: ${client.category-service.uri}
          predicates:
            - Path=/api/categories/group/**
            - Method=POST
          filters:
            - StripPrefix=1
            - Auth

        - id: category_update
          uri: ${client.category-service.uri}
          predicates:
            - Path=/api/categories/group/**
            - Method=PUT
          filters:
            - StripPrefix=1
            - Auth

        - id: category_delete
          uri: ${client.category-service.uri}
          predicates:
            - Path=/api/categories/group/**
            - Method=DELETE
          filters:
            - StripPrefix=1
            - Auth

client:
  auth-service:
    uri: http://localhost
  user-service:
    uri: http://localhost
  operation-service:
    uri: http://localhost
  group-service:
    uri: http://localhost
  account-service:
    uri: http://localhost
  category-service:
    uri: http://localhost

management:
  endpoint:
    health:
      probes:
        enabled: true
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - gateway

server:
  port: 8001

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
