spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
client:
  user-service:
    uri: http://localhost:8787
  auth-service:
    uri: http://localhost:8008
