###
POST {{apiUrl}}/api/auth/login
Content-Type: application/json

{
  "login": "test-login",
  "password": "test-pwd"
}

###
PUT {{apiUrl}}/api/auth/refresh
Content-Type: application/json

{
  "accessToken": {{accessToken}},
  "refreshToken": {{refreshToken}}
}

###
GET {{apiUrl}}/api/users
Authorization: Bearer {{accessToken}}

###
POST {{apiUrl}}/api/auth/register
Content-Type: application/json

{
  "login": "test-login",
  "email": "test.email-1@tt.org",
  "password": "test-pwd",
  "firstName": "test-fn",
  "lastName": "test-ln"
}

###
POST {{operationService}}/operations
Content-Type: application/json

//{
//  "groupId": 123,
//  "description": "Description",
//  "detail": {
//    "type": "INCOME",
//    "fromCategory": 111,
//    "toAccount": 222,
//    "amount": 65.4
//  }
//}
{
  "groupId": 123,
  "description": "Description 456",
  "detail": {
    "type": "TRANSFER",
    "commission": 1,
    "rate": 1.12,
    "resultAmount": 1,
    "fromAccount": 111,
    "toAccount": 222,
    "amount": 65.4
  }
}

###
GET {{apiUrl}}/api/operations/group/1424
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
GET {{operationService}}/operations?groupId=123
Content-Type: application/json
Authorization: Bearer {{accessToken}}