###
POST {{apiUrl}}/api/auth/login
Content-Type: application/json

{
  "login": "test-login",
  "password": "test-pwd"
}

###
POST {{apiUrl}}/api/auth/login
Content-Type: application/json

{
  "login": "test-login",
  "password": "test-pwd"
}

###
GET {{apiUrl}}/api/users
Authorization: Bearer {{accessToken}}

###
GET {{apiUrl}}/api/auth/login
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
PUT {{authServiceUrl}}/auth/refresh
Content-Type: application/json

{
  "accessToken": {{accessToken}},
  "refreshToken": {{refreshToken}}
}


###
POST {{userServiceUrl}}/users/login
Content-Type: application/json

{
  "login": "test-login",
  "password": "test-pwd"
}

###
POST {{userServiceUrl}}/users
Content-Type: application/json

{
  "login": "test-login",
  "email": "test.email@tt.org",
  "password": "test-pwd",
  "firstName": "test-fn",
  "lastName": "test-ln"
}

