--liquibase formatted sql

--changeset carlosray:1
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 select count(1) from information_schema.tables where table_schema = 'public' and table_name = 'balance';
create table balance
(
    id        bigint generated by default as identity
        constraint pk_category
            primary key,
    group_id  bigint                not null,
    entity_id bigint                not null,
    currency  varchar(60)           not null,
    amount    decimal   default 0.0 not null,
    modified  timestamp default now()
);
--rollback drop table balance

--changeset carlosray:2
--preconditions onFail:MARK_RAN
create unique index if not exists balance_group_id_entity_id_key on balance (group_id, entity_id);
--rollback drop index balance_group_id_entity_id_key