db:
  host: localhost
  port: 5432
  name: fa_balance
  username: fa_balance
  password: ""

token:
  internal-key: "default"

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters

spring:
  r2dbc:
    properties:
      ssl: false
      sslMode: disable