spring:
  application:
    name: operation-service
  profiles:
    active: dev
  data:
    mongodb:
      database: ${db.name}
      host: ${db.host}
      port: ${db.port}
      username: ${db.username}
      password: ${db.password}
      repositories:
        type: reactive

management:
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8005
