db:
  host: localhost
  port: 27017
  name: fa_db
  username: fa_user
  password: fa_pwd

token:
  internal-key: "default"

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
    org:
      springframework:
        security: DEBUG