name: App Category Service CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'dev/*'
    paths:
      - 'apps/category-service/**'

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/category-service:${{ github.sha }}

jobs:
  build-jar-docker:
    name: build-jar-docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/dev')
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Cache Depdendencies
        uses: actions/cache@v3.3.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: JDK
        uses: actions/setup-java@v3.12.0
        with:
          java-version: 17
          distribution: adopt
      - name: Build
        run: mvn clean package --projects :category-service-app --also-make --threads=2 --batch-mode
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} --build-arg JAR_DIR=apps/category-service/app/target .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
          
  change-helm-app-version:
    needs: build-jar-docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      
      - name: Commit new helm appVersion
        env:
          APP_VERSION: ${{ github.sha }}
        run: |
          cd .helm/category-service
          sed -i "/^\([[:space:]]*appVersion: \).*/s//\1\"${APP_VERSION}\"/" Chart.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -a -m "Changed helm app version"
          git pull --rebase
          git push
