# Only keeps the last 20 versions per application on GitHub Package Registry.

name: Remove package versions
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * *'
jobs:
  remove-package-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v4
        name: api-gateway clean
        with: 
          package-name: 'fa_tracker/api-gateway'
          package-type: 'container'
          min-versions-to-keep: 3
          
      - uses: actions/delete-package-versions@v4
        name: auth-service clean
        with: 
          package-name: 'fa_tracker/auth-service'
          package-type: 'container'
          min-versions-to-keep: 3
          
      - uses: actions/delete-package-versions@v4
        name: user-service clean
        with: 
          package-name: 'fa_tracker/user-service'
          package-type: 'container'
          min-versions-to-keep: 3
          
      - uses: actions/delete-package-versions@v4
        name: operation-service clean
        with: 
          package-name: 'fa_tracker/operation-service'
          package-type: 'container'
          min-versions-to-keep: 3
          
      - uses: actions/delete-package-versions@v4
        name: category-service clean
        with: 
          package-name: 'fa_tracker/category-service'
          package-type: 'container'
          min-versions-to-keep: 3
          
      - uses: actions/delete-package-versions@v4
        name: account-service clean
        with: 
          package-name: 'fa_tracker/account-service'
          package-type: 'container'
          min-versions-to-keep: 3
      
      - uses: actions/delete-package-versions@v4
        name: group-service clean
        with: 
          package-name: 'fa_tracker/group-service'
          package-type: 'container'
          min-versions-to-keep: 3
